/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConfirmedOwnerUpgradeable } from "./ConfirmedOwnerUpgradeable";
export type { ConfirmedOwnerWithProposalUpgradeable } from "./ConfirmedOwnerWithProposalUpgradeable";
