/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConfirmedOwnerUpgradeable__factory } from "./ConfirmedOwnerUpgradeable__factory";
export { ConfirmedOwnerWithProposalUpgradeable__factory } from "./ConfirmedOwnerWithProposalUpgradeable__factory";
